// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ai-sales-coach-dial-pad/AISalesCoachDialPad.tsx": () => import("../components/mockups/ai-sales-coach-dial-pad/AISalesCoachDialPad.tsx")
};
